### ISSUE TITLE
Export fails on Docker 1.12

### ISSUE THREAD

**Issue by tristanz** [yuuki/droot#7]
When droot export against Docker 1.12-rc2 I get:

API error (400): {"message":"starting container with HostConfig was deprecated since v1.10 and removed in v1.12"}

**Comment by yuuki** [comment]
Thanks for your feedback. I already fixed at [v0.6.2](https://github.com/yuuki/droot/releases/tag/v0.6.2). Please check it.

**Comment by tristanz** [comment]
Ahh, great.  I installed via homebrew.

**Comment by yuuki** [comment]
Sorry, I forgot to update homebrew tap. Now I updated it. You can install droot v0.6.2 via homebrew.
